### ISSUE TITLE
unnecessary changes

### ISSUE THREAD

**Issue by jacekkopecky** [imdone/imdone-core#7]
I'm editing coffeescript and I have a line like this:
```
  # TODO: remove this method and bump the `vim-mode` service version number.
```
It shows up in the iMDone list and that's good. But if I drag it a bit and release it (leaving it in the same place in the same TODO list), it becomes 
```
  # #TODO:0 remove this method and bump the `vim-mode` service version number.
```
Can something be done about the new `#` character? And if I drag an item and release it in the same place, could this avoid triggering priority changes? 

I have very little experience with tools like iMDone, so please treat the last one as a very tentative suggestion: could iMDone treat TODO without priority as an item with a priority fixed at 0, only ever changing its priority if I drag this item to a new place after an item with a priority? I would like that as a configuration option. 

I would be willing to look into submitting PRs for these, but it would take me some time.

**Comment by piascikj** [comment]
Hi Jacek, 

These are very good suggestions, and the second would take very little time.  The first, however; was by design.  I wanted to have a standard list defining prefix, so that a person could place a task anywhere in a comment, markdown or plain text file.  The list prefix is `#` and the task terminator is the end of line.  So when a task is sorted it changes from a code style task to a hash style task.

Code style tasks also have some drawbacks.  You can [read more here](https://github.com/imdone/imdone-core#task-formats)

Thanks for using iMDone.  Are you planning on using it in your classes?  I always thought it would make a great tool for computer science students.

**Comment by jacekkopecky** [comment]
Thanks for the reply @piascikj.

Is it a technical limitation that code-style tasks can't be kept in their original style? See, I haven't used priorities (I find it too fine-grained in my task management), so I don't necessarily like the extra `:0` and that the `#` needs to be right in front of the task keyword.

If we can get my other two suggestions implemented, my code-style tasks without priority wouldn't change to hash-style unless I moved them e.g. from FIXME to DONE.

Would you be willing to consider adding code-style as a fully supported style? I would like the following line 
```
  # TODO: remove this method and bump the `vim-mode` service version number.
```
to change to this if I move this task to DONE: 
```
  # DONE: remove this method and bump the `vim-mode` service version number.
```

As for teaching (well spotted), I don't usually teach programming, but I'm pretty sure I'll be suggesting Atom to the students I work closely with, so *imdone* can easily come up.

**Comment by claytonrcarter** [comment]
I also would like the option of ignoring priority when working with tasks.  I don't manage my tasks that way and would like to be able to drag a task between lists without triggering changes in dozens of other files in my repository.

I recently started IMDone in Atom and have been very, very happy with it.  Excellent work!
